name: Run script
on: [push]

jobs:

  run-script:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo $GITHUB_WORKSPACE/.ci_scripts/install-dependencies.sh

      - name: Run script
        run: python3 $GITHUB_WORKSPACE/src/pcap-tweaker.py $GITHUB_WORKSPACE/traces/http-xiaomi-cloud.pcap
