name: Run script
on: [push]

jobs:

  run-script:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run script
        run: python3 $GITHUB_WORKSPACE/src/pcap-tweaker.py $GITHUB_WORKSPACE/traces/http.pcap
